name = "scansetu-business"
main = "worker.js"
compatibility_date = "2026-09-17"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "ANANTAA_KV"
id = "deb66732eac7425ebdd1ea68257751b5"
